# Generated by Django 4.1 on 2022-09-08 13:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('episodes', models.IntegerField(null=b'I00\n')),
            ],
        ),
        migrations.CreateModel(
            name='Series_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(null=b'I01\n', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('review', models.CharField(max_length=500)),
                ('series_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='lets_rate.series')),
            ],
        ),
        migrations.CreateModel(
            name='Series_genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_genre', models.CharField(max_length=200)),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_genre', to='lets_rate.series')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(null=b'I01\n', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('review', models.CharField(max_length=500)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='lets_rate.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_genre', models.CharField(max_length=200)),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_genre', to='lets_rate.movie')),
            ],
        ),
    ]
