# Generated by Django 4.1 on 2022-09-08 14:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lets_rate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='anonymous', max_length=40)),
                ('review_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('stars', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(max_length=4000)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie_rating',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='series_genre',
            name='genre_id',
        ),
        migrations.RemoveField(
            model_name='series_rating',
            name='series_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='name',
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default='unkown', max_length=3000),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_cover',
            field=models.FileField(default='no_image', upload_to=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(default='no_title', max_length=40),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Movie_genre',
        ),
        migrations.DeleteModel(
            name='Movie_rating',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
        migrations.DeleteModel(
            name='Series_genre',
        ),
        migrations.DeleteModel(
            name='Series_rating',
        ),
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lets_rate.movie'),
        ),
    ]
